### PR TITLE
Do not make unnecessary symlink

### PR DESCRIPTION
**Pull request by Sutrannu**
Signed-off-by: Sutrannu <bbetts@bitwise.io>

### CODE REVIEW

**Comment by peterschwarz** [comment]
What's the context around this change?

**Comment by Sutrannu** [comment]
This should fully implement the use of the nightly docs build mentioned in [d848f5d](https://github.com/hyperledger/grid-website/commit/d848f5daaf5c65eb429e19ba885bf70841244802), where line being removed were added.

**Comment by Sutrannu** [comment]
@peterschwarz, the change from using the supply-chain docs to the grid repo nightly docs left this symlink creation is place, creating a broken symlink.
Jenkins fails when zipping artifacts with broken links. The change should have been in place earlier, but was not noticed until deployment broke.

**Comment by peterschwarz** [comment]
Good context; could probably go in the commit message

**Comment by Sutrannu** [comment]
Commit body updated for context.

**Pull request merged**
